name: CI Windows/MSVC

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows 2019 MSVC 2019 Win32",
            os: windows-2019,
            build_type: Debug,
            generator: "Visual Studio 16 2019",
            architecture: "Win32"
          }
          - {
            name: "Windows 2022 MSVC 2022 Win32 C++11",
            os: windows-2022,
            build_type: Debug,
            generator: "Visual Studio 17 2022",
            architecture: "Win32",
            cxx_standard: 11
          }
          - {
            name: "Windows 2022 MSVC 2022 Win32 C++14",
            os: windows-2022,
            build_type: Debug,
            generator: "Visual Studio 17 2022",
            architecture: "Win32",
            cxx_standard: 14
          }
          - {
            name: "Windows 2022 MSVC 2022 Win32 C++17",
            os: windows-2022,
            build_type: Debug,
            generator: "Visual Studio 17 2022",
            architecture: "Win32",
            cxx_standard: 17
          }
          - {
            name: "Windows 2022 MSVC 2022 Win32 C++20",
            os: windows-2022,
            build_type: Debug,
            generator: "Visual Studio 17 2022",
            architecture: "Win32",
            cxx_standard: 20
          }
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: |
          cmake -S . -B build \
            -G "${{ matrix.config.generator }}" \
            -A ${{ matrix.config.architecture }} \
            -DENABLE_TESTING=ON \
            -DOVERRIDE_CXX_STANDARD_FOR_TESTS=${{ matrix.config.cxx_standard }}
          cmake --build build --config ${{ matrix.config.build_type }} -j
      - name: Run tests
        run: |
          build/tests/Debug/FakeIt_tests.exe
